return {
  { '[', ']' },
  { '(', ')' },
  { '{', '}' },
  { '-', '+' },
  { '<', '>' },
  { "'", '"' },
  { '&&', '||' },
  { 'or', 'and' },
  { 'get', 'set' },
  { 'on', 'off' },
  { 'all', 'none' },
  { 'allow', 'deny' },
  { 'true', 'false' },
  { '$True', '$False' },
  { 'enable', 'disable' },
  { 'Enable', 'Disable' },
  { 'enabled', 'disabled' },
  { 'Enabled', 'Disabled' },
  { 'public', 'protected', 'private' },
  { 'IsTrue', 'IsFalse' },
  { 'IsNull', 'IsNotNull' },
}
