return {
    -- symbols
    { '[', ']' },
    { '(', ')' },
    { '{', '}' },
    { '-', '+' },
    { '*', '/' },
    { '<', '>' },
    { "'", '"' },
    { '&&', '||' },
    -- short words
    { 'or', 'and' },
    { 'on', 'off' },
    { 'up', 'down' },
    { 'get', 'set' },
    { 'yes', 'no' },
    { 'Yes', 'No' },
    { 'YES', 'NO' },
    { 'min', 'max' },
    { 'asc', 'desc' },
    { 'ASC', 'DESC' },
    { 'top', 'bottom' },
    { 'all', 'none' },
    { 'add', 'remove' },
    { 'row', 'column' },
    { 'prev', 'next' },
    { 'head', 'tail' },
    { 'push', 'pop' },
    { 'send', 'receive' },
    { 'show', 'hide' },
    { 'open', 'close' },
    { 'read', 'write' },
    { 'lock', 'unlock' },
    { 'load', 'unload' },
    { 'allow', 'deny' },
    { 'TODO', 'DONE' },
    { 'todo', 'done' },
    { 'first', 'last' },
    { 'inner', 'outer' },
    { 'true', 'false' },
    { 'TRUE', 'FALSE' },
    { 'start', 'stop' },
    { 'Start', 'Stop' },
    { 'begin', 'end' },
    { 'Begin', 'End' },
    { 'above', 'below' },
    { 'focus', 'blur' },
    { 'before', 'after' },
    { 'width', 'height' },
    { 'active', 'inactive' },
    { 'source', 'target' },
    { 'import', 'export' },
    { '$True', '$False' },
    { 'enable', 'disable' },
    { 'Enable', 'Disable' },
    { 'enabled', 'disabled' },
    { 'Enabled', 'Disabled' },
    { 'encode', 'decode' },
    { 'Encode', 'Decode' },
    { 'attach', 'detach' },
    { 'Attach', 'Detach' },
    { 'resolve', 'reject' },
    { 'encrypt', 'decrypt' },
    { 'Encrypt', 'Decrypt' },
    { 'visible', 'hidden' },
    { 'include', 'exclude' },
    { 'connect', 'disconnect' },
    { 'Connect', 'Disconnect' },
    { 'success', 'failure' },
    { 'subscribe', 'unsubscribe' },
    { 'Subscribe', 'Unsubscribe' },
    { 'serialize', 'deserialize' },
    { 'Serialize', 'Deserialize' },
    { 'horizontal', 'vertical' },
    { 'Horizontal', 'Vertical' },
    -- multi-value chains
    { 'public', 'protected', 'private' },
    { 'left', 'center', 'right' },
}

